appId: org.bibletranslationtools.writer
---
- setOrientation: LANDSCAPE_LEFT
- scrollUntilVisible:
    element: "Create offline Account"
    direction: DOWN
    timeout: 5000
    centerElement: true
- tapOn:
    text: "Create offline Account"
    waitToSettleTimeoutMs: 200
- assertVisible: "Your Name or Pseudonym"
- tapOn:
    text: "Your Name or Pseudonym"
    waitToSettleTimeoutMs: 200
- inputText: "Test User"
- hideKeyboard
- tapOn: "Continue"
- tapOn: "Continue"
- extendedWaitUntil:
    visible: "Terms of Use"
    timeout: 5000
- scroll
- tapOn:
    text: "I Agree"
    rightOf: "No Thanks"
- extendedWaitUntil:
    visible: "Your Translation Projects"
    timeout: 3000
- tapOn:
    text: "More Options"
    waitToSettleTimeoutMs: 200
- tapOn:
    text: "Settings"
    waitToSettleTimeoutMs: 200
- assertVisible: "General"
- tapOn:
    text: "back"
    waitToSettleTimeoutMs: 200
- assertVisible: "Your Translation Projects"
